version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:${IMG_TAG}
    #image: sksat/papermc_docker:github-actions
    #build:
    #  context: .
    #  args:
    #    - MINECRAFT_VERSION=$MINECRAFT_VERSION
    #    - PAPER_VERSION=$PAPER_VERSION
    #    - PAPER_COMMIT=$PAPER_COMMIT
    restart: always

    stdin_open: true
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx1G"
    volumes:
      - ./data:/app
