on:
  schedule:
    - cron:  '15 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: update/paper

      - name: rebase
        shell: bash
        run: git pull --rebase origin develop

      - name: update Paper commit
        shell: bash
        run: ./update.sh

      - name: check diff
        shell: bash
        run: |
          if [[ $(git diff) ]]; then
            echo "::set-env name=HAS_DIFF::true";
          fi

      - name: commit & push
        if: env.HAS_DIFF == 'true'
        shell: bash
        run: |
          git add .env
          source .env
          git commit -m "update: Paper to ${PAPER_COMMIT}"
          git push origin update/paper
