name: Build Container Image

on:
  push:
    paths:
      - 'build.sh'
      - 'health.sh'
      - 'utils/download-mc-monitor.sh'
      - 'entrypoint.sh'
      - 'Dockerfile'
      - '.dockerignore'
      - '.env'
      - '.github/workflows/build-image.yml'
      - 'utils/set-tags.sh'
      - 'test/startup.sh'
      - 'test/docker-compose.yml'
      - 'test/server.properties'

jobs:
  build_jar:
    runs-on: ubuntu-latest

    outputs:
      MINECRAFT_VERSION: ${{ steps.paper-commit.outputs.MINECRAFT_VERSION }}
      PAPER_VERSION: ${{ steps.paper-commit.outputs.PAPER_VERSION }}
      PAPER_COMMIT: ${{ steps.paper-commit.outputs.PAPER_COMMIT }}

    steps:
      - uses: actions/checkout@v2

      - name: Get Paper commit
        id: paper-commit
        shell: bash
        run: |
          source .env
          echo "::set-output name=MINECRAFT_VERSION::${MINECRAFT_VERSION}"
          echo "::set-output name=PAPER_VERSION::${PAPER_VERSION}"
          echo "::set-output name=PAPER_COMMIT::${PAPER_COMMIT}"

      - name: cache paperclip
        id: cache-paperclip
        uses: actions/cache@v2
        with:
          path: Paper/paperclip-${{ steps.paper-commit.outputs.PAPER_COMMIT }}.jar
          key: paperclip-${{ runner.os }}-${{ steps.paper-commit.outputs.PAPER_COMMIT }}

      - name: clone Paper
        if: steps.cache-paperclip.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: PaperMC/Paper
          path: Paper
          ref: ${{ steps.paper-commit.outputs.PAPER_COMMIT }}

      - name: setup Java
        if: steps.cache-paperclip.outputs.cache-hit != 'true'
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt-openj9'
          java-version: '16.0.2'
          cache: 'gradle'

      - name: Build jar
        if: steps.cache-paperclip.outputs.cache-hit != 'true'
        run: |
          ls
          bash ./build.sh

  base_img_matrix:
    name: Generate Base Image matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - name: Set Base Image matrix
        id: set-matrix
        run: |
          imgs=$(./utils/java.sh base-img adopt | tr '\n' ' ')
          imgs=$(echo "${imgs}" | sed -e 's/ /, /g')
          echo -n '::set-output name=matrix::[' \
          && echo -n ${imgs} \
          && echo ']'

  build_image:
    needs: [build_jar, base_img_matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_img: ${{ fromJSON(needs.base_img_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: clone Paper
        uses: actions/checkout@v2
        with:
          repository: PaperMC/Paper
          path: Paper
          ref: ${{ needs.build_jar.outputs.PAPER_COMMIT }}

      - name: restore paperclip cache
        uses: actions/cache@v2
        with:
          path: Paper/paperclip.jar
          key: paperclip-${{ runner.os }}-${{ needs.build_jar.outputs.PAPER_COMMIT }}

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: ghcr.io/${{ github.repository }},sksat/${{ github.event.repository.name }}

      - name: Set Tags
        id: tags
        shell: bash
        env:
          JDK: ${{ matrix.jdk }}
        run: |
          tags=$(cat << EOS | ./utils/set-tags.sh
          ${{ steps.meta.outputs.tags }}
          EOS
          )
          echo "tags: ${tags}"
          tags="${tags//'%'/'%25'}"
          tags="${tags//$'\n'/'%0A'}"
          tags="${tags//$'\r'/'%0D'}"
          echo "::set-output name=tags::${tags}"

      - name: Set base image
        id: set_base
        shell: bash
        run: |
          if [[ ${{ matrix.jdk }} == 'openjdk' ]]; then
            echo "::set-output name=base_img::openjdk:16.0.2-slim-buster"
          elif [[ ${{ matrix.jdk }} == 'adopt' ]]; then
            echo "::set-output name=base_img::adoptopenjdk/openjdk16:alpine-jre"
          fi

      - name: Login to ghcr.io
        if: ${{ github.event_name }} != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: ${{ github.event_name }} != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: sksat
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            "MINECRAFT_VERSION=${{ needs.build_jar.outputs.MINECRAFT_VERSION }}"
            "PAPER_VERSION=${{ needs.build_jar.outputs.PAPER_VERSION }}"
            "PAPER_COMMIT=${{ needs.build_jar.outputs.PAPER_COMMIT }}"
            "BASE_IMG=${{ steps.set_base.outputs.base_img }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  test:
    needs: build_image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: ["openjdk", "adoptopenjdk"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python --version
          python3 -m pip install mcstatus

      - name: startup test
        run: |
          ./test/startup.sh "${GITHUB_REF#refs/heads/}-${{ matrix.jdk }}"
