name: validate renovate

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/workflows/validate-renovate.yml'

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator
